// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Tool
{
    internal sealed partial class Vsix
    {
        public const string Id = "Tool.a5d717c6-a303-41bc-a432-416ccc443bc9";
        public const string Name = "Tool extension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Lukáš Kratochvíl";
        public const string Tags = "";
    }
}
