// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FirstExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "FirstExtension.283353b3-d172-4d24-846a-8f7b5db6553d";
        public const string Name = "FirstExtension";
        public const string Description = @"First extension";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Lukáš Kratochvíl";
        public const string Tags = "";
    }
}
