// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FirstVsExtensibilityExtensionTests
{
    internal sealed partial class Vsix
    {
        public const string Id = "FirstVsExtensibilityExtensionTests.8c238ac8-ad5f-4a79-8fdc-3852b172e270";
        public const string Name = "FirstVsExtensibilityExtensionTests";
        public const string Description = @"VisualStudio.Extensibility Extension with VSSDK Compatibility.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Publisher name";
        public const string Tags = "";
    }
}
