// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FirstVsSdkExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "FirstVsSdkExtension.1191d2ee-7848-4ed3-a4e5-1728341d1adb";
        public const string Name = "FirstVsSdkExtension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Lukáš Kratochvíl";
        public const string Tags = "";
    }
}
