// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FirstVsSdkExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string FirstVsSdkExtensionString = "174a2c23-b994-4125-ba0f-cfedbe88e79c";
        public static Guid FirstVsSdkExtension = new Guid(FirstVsSdkExtensionString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int FirstMenuGroup = 0x0001;
        public const int FirstCommand = 0x0100;
        public const int ShowToolWindow = 0x0101;
    }
}